# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_birthday'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='added_by',
            field=models.ManyToManyField(related_name='jobs_added', to='login.User'),
        ),
    ]
